/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as homePageIndexImport } from './routes/(homePage)/index'
import { Route as userMyBooksImport } from './routes/(user)/my-books'
import { Route as booksAdminBooksAdminReferencesImport } from './routes/(booksAdmin)/books-admin-references'
import { Route as booksAdminBooksAdminImport } from './routes/(booksAdmin)/books-admin'
import { Route as booksAdminBookAdminCreateImport } from './routes/(booksAdmin)/book-admin-create'
import { Route as booksBooksStoreImport } from './routes/(books)/books-store'
import { Route as booksAdminBookAdminBookIdImport } from './routes/(booksAdmin)/book-admin.$bookId'
import { Route as booksBookStoreBookIdImport } from './routes/(books)/book-store.$bookId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const homePageIndexRoute = homePageIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const userMyBooksRoute = userMyBooksImport.update({
  path: '/my-books',
  getParentRoute: () => rootRoute,
} as any)

const booksAdminBooksAdminReferencesRoute =
  booksAdminBooksAdminReferencesImport.update({
    path: '/books-admin-references',
    getParentRoute: () => rootRoute,
  } as any)

const booksAdminBooksAdminRoute = booksAdminBooksAdminImport.update({
  path: '/books-admin',
  getParentRoute: () => rootRoute,
} as any)

const booksAdminBookAdminCreateRoute = booksAdminBookAdminCreateImport.update({
  path: '/book-admin-create',
  getParentRoute: () => rootRoute,
} as any)

const booksBooksStoreRoute = booksBooksStoreImport.update({
  path: '/books-store',
  getParentRoute: () => rootRoute,
} as any)

const booksAdminBookAdminBookIdRoute = booksAdminBookAdminBookIdImport.update({
  path: '/book-admin/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const booksBookStoreBookIdRoute = booksBookStoreBookIdImport.update({
  path: '/book-store/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(books)/books-store': {
      preLoaderRoute: typeof booksBooksStoreImport
      parentRoute: typeof rootRoute
    }
    '/(booksAdmin)/book-admin-create': {
      preLoaderRoute: typeof booksAdminBookAdminCreateImport
      parentRoute: typeof rootRoute
    }
    '/(booksAdmin)/books-admin': {
      preLoaderRoute: typeof booksAdminBooksAdminImport
      parentRoute: typeof rootRoute
    }
    '/(booksAdmin)/books-admin-references': {
      preLoaderRoute: typeof booksAdminBooksAdminReferencesImport
      parentRoute: typeof rootRoute
    }
    '/(user)/my-books': {
      preLoaderRoute: typeof userMyBooksImport
      parentRoute: typeof rootRoute
    }
    '/(homePage)/': {
      preLoaderRoute: typeof homePageIndexImport
      parentRoute: typeof rootRoute
    }
    '/(books)/book-store/$bookId': {
      preLoaderRoute: typeof booksBookStoreBookIdImport
      parentRoute: typeof rootRoute
    }
    '/(booksAdmin)/book-admin/$bookId': {
      preLoaderRoute: typeof booksAdminBookAdminBookIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LoginRoute,
  booksBooksStoreRoute,
  booksAdminBookAdminCreateRoute,
  booksAdminBooksAdminRoute,
  booksAdminBooksAdminReferencesRoute,
  userMyBooksRoute,
  homePageIndexRoute,
  booksBookStoreBookIdRoute,
  booksAdminBookAdminBookIdRoute,
])

/* prettier-ignore-end */
