/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as homePageIndexImport } from './routes/(homePage)/index'
import { Route as userMyBooksImport } from './routes/(user)/my-books'
import { Route as booksAdminBooksAdminImport } from './routes/(booksAdmin)/books-admin'
import { Route as booksBooksStoreImport } from './routes/(books)/books-store'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const homePageIndexRoute = homePageIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const userMyBooksRoute = userMyBooksImport.update({
  path: '/my-books',
  getParentRoute: () => rootRoute,
} as any)

const booksAdminBooksAdminRoute = booksAdminBooksAdminImport.update({
  path: '/books-admin',
  getParentRoute: () => rootRoute,
} as any)

const booksBooksStoreRoute = booksBooksStoreImport.update({
  path: '/books-store',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(books)/books-store': {
      preLoaderRoute: typeof booksBooksStoreImport
      parentRoute: typeof rootRoute
    }
    '/(booksAdmin)/books-admin': {
      preLoaderRoute: typeof booksAdminBooksAdminImport
      parentRoute: typeof rootRoute
    }
    '/(user)/my-books': {
      preLoaderRoute: typeof userMyBooksImport
      parentRoute: typeof rootRoute
    }
    '/(homePage)/': {
      preLoaderRoute: typeof homePageIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LoginRoute,
  booksBooksStoreRoute,
  booksAdminBooksAdminRoute,
  userMyBooksRoute,
  homePageIndexRoute,
])

/* prettier-ignore-end */
